version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  assignees:
  - hra42
  groups:
    patch-updates:
      patterns:
      - "*"
      update-types:
      - "patch"
    minor-updates:
      patterns:
      - "*"
      update-types:
      - "minor"
